# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: es6-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs4.3

defaults:
  stage: dev
  region: eu-west-1


functions:
  create:
    handler: lib/handlers/auth.create
    events:
      - http:
          path: create
          method: post
  login:
    handler: lib/handlers/auth.login
    events:
      - http:
          path: login
          method: post
  whoami:
    handler: lib/handlers/auth.whoami
    events:
      - http:
          path: whoami
          method: get
          
  forgot:
    handler: lib/handlers/auth.forgot
    events:
      - http:
          path: forgot
          method: post

          
  graphql:
    handler: lib/handlers/graphql.graph
    events:
      - http:
          path: graphql
          method: post


package:
  include:
    - lib
    - node_modules
  exclude:
    - .gitignore
    - .synk
    - .travis.yml
    - package.json
    - README.md

plugins:
  - serverless-scriptable-plugin
  
custom:
  scriptHooks:
    before:deploy:createDeploymentArtifacts: build/package.js